import {createRoot} from 'react-dom/client';
import {useEffect, useRef, useState} from 'react';
import {ArrowDown, ArrowRight, Check, ChevronDown, Mic, Pause, Play, Send, Settings2, Volume2} from 'lucide-react';
import './styles.css';
const a=(p:string)=>import.meta.env.BASE_URL+p;
const plans=[['01','VOXA'],['02','HALO'],['03','FLOW'],['04','ÉCRAN'],['05','VOIX'],['06','ESPACE'],['07','RÉGLAGES']];
const accents=['#6d36a8','#0f6f81','#9b5de5','#a54832','#2d6b4f'];
function App(){
 const [active,setActive]=useState('01'); const [paused,setPaused]=useState(false); const [query,setQuery]=useState(''); const [reply,setReply]=useState(''); const [listening,setListening]=useState(false); const [accent,setAccent]=useState(localStorage.getItem('voxa-accent')||accents[0]); const [dark,setDark]=useState(false); const video=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const els=[...document.querySelectorAll<HTMLElement>('[data-plan]')];const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');setActive(e.target.getAttribute('data-plan')||'01')}}),{threshold:.42});els.forEach(x=>ob.observe(x));return()=>ob.disconnect()},[]);
 useEffect(()=>{localStorage.setItem('voxa-accent',accent)},[accent]);
 const run=()=>{if(!query.trim())return;setReply('J’ai compris votre demande. Voici le plan préparé par HALO : comprendre, vérifier puis demander votre accord avant l’action.')};
 const listen=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setReply('La dictée n’est pas disponible dans ce navigateur. Vous pouvez écrire votre commande.');return}const r=new SR();r.lang='fr-FR';r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=(e:any)=>setQuery(e.results[0][0].transcript);r.start()};
 return <div className={dark?'site dark':'site'} style={{'--accent':accent} as React.CSSProperties}>
  <header className="topbar"><a className="wordmark" href="#p01"><img src={a('robots/voxa-logo.jpg')}/>VOXA</a><nav>{plans.map(([n,t])=><a className={active===n?'current':''} href={'#p'+n} key={n}>{n}<span>{t}</span></a>)}</nav><button className="settings" onClick={()=>setDark(!dark)} aria-label="Changer le thème"><Settings2 size={17}/></button></header>
  <aside className="progress">{plans.map(([n])=><a className={active===n?'on':''} href={'#p'+n} key={n}>{n}</a>)}</aside>
  <main>
   <section id="p01" data-plan="01" className="plan plan-one"><div className="plan-label">PLAN 01 / IDENTITÉ</div><div className="one-grid"><div className="portrait"><img src={a('robots/voxa-hero.jpg')} alt="VOXA, robot blanc"/><span>VOXA / 01</span></div><div className="one-copy"><p className="kicker">Une voix. Toutes les IA. Toutes les actions.</p><h1>Votre voix vient<br/><i>de gagner des mains.</i></h1><p>VOXA comprend votre intention et vous aide à la transformer en action, sans vous enlever le contrôle.</p><a className="line-button" href="#p02">Découvrir HALO <ArrowDown size={15}/></a></div></div></section>
   <section id="p02" data-plan="02" className="plan plan-two"><div className="plan-label">PLAN 02 / PRÉSENCE</div><div className="two-grid"><div className="two-copy"><p className="kicker">Le geste derrière l’intention.</p><h2>HALO arrive<br/><i>quand VOXA comprend.</i></h2><p>Le robot noir est l’agent : il prépare une action, l’explique et attend votre accord. Rien n’est présenté comme magique.</p><div className="state"><b/><span>HALO / PRÊT À ÉCOUTER</span></div></div><div className="halo-portrait"><img src={a('robots/halo.jpg')} alt="HALO, robot noir"/><span>HALO / 02</span></div></div></section>
   <section id="p03" data-plan="03" className="plan plan-three"><div className="plan-label">PLAN 03 / FLOW</div><div className="flow-frame"><video ref={video} poster={a('media/flow-poster.jpg')} src={a('media/flow-robots.mp4')} autoPlay muted playsInline/><div className="flow-copy"><p className="kicker">Deux présences. Une intention.</p><h2>Les robots<br/><i>vous regardent agir.</i></h2><p>La vidéo Flow reste la pièce centrale. Le texte occupe l’espace vide au centre sans recouvrir les robots.</p><button className="round" onClick={()=>{if(video.current?.paused){video.current.play();setPaused(false)}else{video.current?.pause();setPaused(true)}}}>{paused?<Play size={16}/>:<Pause size={16}/>}</button></div></div></section>
   <section id="p04" data-plan="04" className="plan plan-four"><div className="plan-label">PLAN 04 / L’ÉCRAN</div><div className="screen-intro"><p className="kicker">Pas un faux ordinateur. Une vraie interface.</p><h2>Une fenêtre vers<br/><i>votre intention.</i></h2></div><div className="screen-only"><div className="screen-bar"><span className="dot red"/><span className="dot yellow"/><span className="dot green"/><span>VOXA / ESPACE DE TRAVAIL</span></div><div className="screen-content"><aside><b>V</b><span className="active">Accueil</span><span>Conversations</span><span>Plans</span><span>Réglages</span></aside><div className="screen-main"><div className="screen-head"><span>Bonjour, que prépare-t-on ?</span><small>● HALO en ligne</small></div><div className="message"><img src={a('robots/halo.jpg')} alt="HALO"/><div><small>HALO</small><p>{reply||'Je suis prêt à transformer une demande en plan clair.'}</p>{reply&&<div className="plan-result"><Check size={13}/> Plan prêt · confirmation requise</div>}</div></div><div className="command"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="Dites à HALO quoi faire…"/><button onClick={listen} className={listening?'listening':''}><Mic size={16}/></button><button onClick={run}><Send size={16}/></button></div></div></div></div></section>
   <section id="p05" data-plan="05" className="plan plan-five"><div className="plan-label">PLAN 05 / LA VOIX</div><div className="voice-grid"><div><p className="kicker">Commande vocale</p><h2>Parlez comme<br/><i>vous pensez.</i></h2><p>Appuyez sur le micro, donnez une demande et vérifiez le texte compris par VOXA avant de poursuivre.</p><button className="voice-button" onClick={listen}><Mic size={19}/>{listening?'Écoute en cours…':'Essayer la dictée'}</button></div><div className="voice-orbit"><div className="wave w1"/><div className="wave w2"/><div className="voice-core"><Volume2 size={25}/></div></div></div></section>
   <section id="p06" data-plan="06" className="plan plan-six"><div className="plan-label">PLAN 06 / L’ESPACE</div><div className="space-grid"><div className="space-copy"><p className="kicker">VOXA / HALO</p><h2>Une application<br/><i>qui reste lisible.</i></h2><p>Conversations, plans d’action et historique se trouvent au même endroit. HALO est l’agent, VOXA est la voix et l’interface reste compréhensible.</p></div><div className="mini-space"><div className="mini-top">ESPACE PERSONNEL <span>●</span></div><div className="mini-row"><img src={a('robots/voxa.jpg')} alt="VOXA"/><div><b>VOXA</b><span>Contexte compris</span></div></div><div className="mini-row"><img src={a('robots/halo.jpg')} alt="HALO"/><div><b>HALO</b><span>Plan en attente de validation</span></div></div></div></div></section>
   <section id="p07" data-plan="07" className="plan plan-seven"><div className="plan-label">PLAN 07 / RÉGLAGES</div><div className="seven-grid"><div><p className="kicker">Votre interface, vos règles.</p><h2>Puissante quand<br/><i>vous le décidez.</i></h2><p>Choisissez votre couleur d’accent, votre fournisseur et la quantité d’animation. Les clés restent masquées dans l’interface.</p></div><div className="preferences"><label>Couleur d’accent</label><div className="color-row">{accents.map(c=><button key={c} style={{background:c}} className={accent===c?'picked':''} onClick={()=>setAccent(c)} aria-label="Choisir cette couleur"/>)}</div><label>Thème</label><div className="theme-row"><button onClick={()=>setDark(false)} className={!dark?'picked':''}>Clair</button><button onClick={()=>setDark(true)} className={dark?'picked':''}>Noir</button></div><div className="provider"><span>Fournisseur IA</span><b>Gemini · masqué</b><ChevronDown size={15}/></div></div></div><div className="end"><a className="primary" href="#p01">Rejouer l’expérience <ArrowRight size={15}/></a></div></section>
  </main><footer><span>VOXA</span><span>Une voix. Toutes les IA. Toutes les actions.</span><span>Prototype en validation · aucune publication automatique</span></footer>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
