import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence, motion, useScroll, useSpring, useTransform} from 'motion/react';
import {ArrowRight, Check, ChevronDown, Command, Copy, Download, Menu, Mic, Pause, Play, RotateCcw, Send, Settings2, Sparkles, X, Zap} from 'lucide-react';
import './styles.css';

const accents = {violet:'#9b6cff', blue:'#5d8cff', cyan:'#36d8d1', rose:'#ff6f9f', lime:'#b4df67'};
type Theme='dark'|'light';
function App(){
 const [theme,setTheme]=useState<Theme>('dark'); const [accent,setAccent]=useState('violet'); const [settings,setSettings]=useState(false); const [menu,setMenu]=useState(false); const [demo,setDemo]=useState(false);
 const [query,setQuery]=useState(''); const [answer,setAnswer]=useState(''); const [copied,setCopied]=useState(false);
 const color=accents[accent as keyof typeof accents];
 const ask=()=>{if(!query.trim())return; setAnswer('Je prépare cette action en toute sécurité. Dans VOXA, vous pourrez connecter votre IA, vérifier le plan, puis confirmer son exécution.');};
 const copy=()=>{navigator.clipboard?.writeText(answer);setCopied(true);setTimeout(()=>setCopied(false),1300)};
 return <div className={`app ${theme}`} style={{'--accent':color} as React.CSSProperties}>
  <header className="nav"><a className="brand" href="#top"><img src="/brand/voxa-logo.jpg"/><span>VOXA</span></a><nav className={menu?'open':''}><a href="#vision" onClick={()=>setMenu(false)}>Vision</a><a href="#halo" onClick={()=>setMenu(false)}>HALO</a><a href="#demo" onClick={()=>setMenu(false)}>Démo</a><a href="#faq" onClick={()=>setMenu(false)}>FAQ</a><button className="nav-cta" onClick={()=>setDemo(true)}>Essayer VOXA <ArrowRight size={16}/></button></nav><button className="icon mobile" aria-label="Menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button className="icon" aria-label="Personnaliser" onClick={()=>setSettings(!settings)}><Settings2 size={19}/></button></header>
  <AnimatePresence>{settings&&<motion.aside initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:20}} className="settings"><div className="settings-head"><span>Personnaliser VOXA</span><button className="icon" onClick={()=>setSettings(false)}><X size={17}/></button></div><p>Votre interface, votre rythme.</p><label>Thème</label><div className="theme-switch"><button className={theme==='dark'?'active':''} onClick={()=>setTheme('dark')}>Noir</button><button className={theme==='light'?'active':''} onClick={()=>setTheme('light')}>Clair</button></div><label>Couleur d’accent</label><div className="swatches">{Object.keys(accents).map(k=><button key={k} aria-label={k} className={accent===k?'selected':''} style={{background:accents[k as keyof typeof accents]}} onClick={()=>setAccent(k)}/>)}</div><small>Ce réglage est mémorisé uniquement sur cet appareil.</small></motion.aside>}</AnimatePresence>
  <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="pulse"/> Assistant vocal personnel · HALO inside</p><h1>Votre voix vient<br/><em>de gagner des mains.</em></h1><p className="lead">Une voix. Toutes les IA. Toutes les actions. VOXA transforme une intention claire en une action que vous pouvez comprendre, vérifier et lancer.</p><div className="actions"><button className="primary" onClick={()=>setDemo(true)}>Parler à VOXA <ArrowRight size={17}/></button><a className="text-link" href="#vision">Découvrir la vision <ChevronDown size={16}/></a></div><div className="trust"><span><Check size={14}/> PWA installable</span><span><Check size={14}/> Pas de télémétrie par défaut</span></div></div><div className="hero-media"><div className="media-label"><span>HALO / 01</span><span>Vision en mouvement</span></div><video autoPlay muted playsInline poster="/media/halo-poster.jpg" src="/media/halo-hero.mp4"/><div className="media-caption">Deux présences. Une interface entre votre intention et le monde.</div></div></section>
   <section className="marquee"><span>UNDERSTAND</span><i>✦</i><span>PLAN</span><i>✦</i><span>ACT</span><i>✦</i><span>UNDERSTAND</span><i>✦</i><span>PLAN</span><i>✦</i><span>ACT</span></section>
   <section id="vision" className="split section"><div className="section-index">01 / LA VISION</div><div><h2>L’IA ne devrait pas seulement répondre.<br/><span>Elle devrait vous aider à avancer.</span></h2><p className="body">VOXA rassemble vos modèles préférés dans une même voix et ajoute ce qui leur manque : le contexte, un plan lisible et la capacité d’agir avec votre accord.</p><div className="feature-line"><b>01</b><div><strong>Une seule voix</strong><p>Choisissez votre fournisseur, gardez vos clés masquées et changez de modèle sans changer vos habitudes.</p></div></div><div className="feature-line"><b>02</b><div><strong>Un plan avant l’action</strong><p>Chaque demande importante devient une suite d’étapes que vous pouvez modifier, arrêter ou confirmer.</p></div></div></div></section>
   <section id="halo" className="halo-section section"><div className="halo-visual"><div className="halo-ring r1"/><div className="halo-ring r2"/><div className="halo-core"><span>H</span></div><span className="halo-state">HALO · PRÊT</span></div><div className="halo-copy"><div className="section-index">02 / HALO</div><h2>Parlez naturellement.<br/><span>Gardez le contrôle.</span></h2><p className="body">HALO écoute, comprend et prépare. Il ne lance pas une action sensible sans vous la montrer. Comme JARVIS dans l’intention, mais avec des limites et des permissions réelles.</p><div className="state-list"><span className="active"><i/> Écoute</span><span><i/> Comprend</span><span><i/> Prépare</span><span><i/> Demande votre accord</span></div></div></section>
   <section id="demo" className="demo-section section"><div className="demo-heading"><div className="section-index">03 / DÉMONSTRATION</div><h2>Une interface qui<br/><span>fait vraiment quelque chose.</span></h2><p className="body">Essayez un aperçu interactif. Cette scène est clairement une démonstration marketing ; les actions disponibles dans l’app seront réelles et signalées.</p></div><div className="laptop"><div className="laptop-screen"><div className="window-bar"><span className="traffic red"/><span className="traffic yellow"/><span className="traffic green"/><span className="window-title">voxa / workspace</span></div><div className="workspace"><aside><div className="mini-brand">V</div><span className="side-active">Accueil</span><span>Conversations</span><span>Automations</span><span>Réglages</span></aside><div className="work-main"><div className="work-top"><span>Bonjour. Que fait-on ?</span><span className="online"><i/> HALO en ligne</span></div><div className="chat-card"><div className="avatar">H</div><div><small>HALO · maintenant</small><p>{answer||'Je suis prêt. Demandez-moi de chercher, organiser ou préparer une action.'}</p>{answer&&<div className="approval"><span>Plan préparé</span><button onClick={()=>setAnswer('Action confirmée. Le résultat apparaîtra ici.')}>Confirmer</button></div>}</div></div><div className="command"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Dites à HALO quoi faire…"/><button aria-label="Dictée"><Mic size={17}/></button><button aria-label="Envoyer" onClick={ask}><Send size={17}/></button></div><div className="suggestions"><button onClick={()=>setQuery('Ouvre une recherche sur les dernières nouvelles de mon projet')}>Rechercher une information <ArrowRight size={13}/></button><button onClick={()=>setQuery('Crée une note avec cette idée')}>Créer une note <ArrowRight size={13}/></button></div></div></div></div><div className="laptop-base"/></div></section>
   <section className="privacy section"><div className="privacy-card"><Sparkles size={22}/><div><div className="section-index">04 / CONFIANCE</div><h2>Puissante, pas opaque.</h2><p>Vos clés restent masquées. Votre historique reste sur votre appareil par défaut. Pas de télémétrie obligatoire. VOXA vous montre ce qu’il comprend avant d’agir.</p></div><a href="#faq">Nos engagements <ArrowRight size={16}/></a></div></section>
   <section id="faq" className="faq section"><div className="section-index">05 / FAQ</div><h2>Les réponses simples<br/><span>aux vraies questions.</span></h2>{['VOXA fonctionne-t-il hors connexion ?','Est-ce que VOXA contrôle tout mon ordinateur ?','Puis-je choisir mon fournisseur d’IA ?','Puis-je installer VOXA sur un téléphone ?'].map((q,i)=><details key={q}><summary><span>0{i+1}</span>{q}<ChevronDown size={18}/></summary><p>{i===0?'Une partie oui : l’interface, vos réglages et certaines fonctions restent disponibles. Les réponses IA et les actions en ligne nécessitent la connexion du fournisseur concerné.':i===1?'Pas depuis une simple PWA. Le contrôle desktop complet est prévu dans une application dédiée, avec permissions explicites et bouton d’arrêt.':i===2?'Oui. VOXA est pensé pour Gemini, OpenAI-compatible, Anthropic, Ollama et d’autres fournisseurs, avec des clés affichées de manière masquée.':'Oui, comme PWA installable sur Android et ordinateur. iOS conserve les limites normales des applications web.'}</p></details>)}</section>
   <section className="final section"><p className="eyebrow"><span className="pulse"/> Votre prochaine interface</p><h2>Donnez une voix<br/><em>à vos intentions.</em></h2><button className="primary" onClick={()=>setDemo(true)}>Essayer l’expérience <ArrowRight size={17}/></button></section>
  </main><footer><div className="brand"><img src="/brand/voxa-logo.jpg"/><span>VOXA</span></div><span>Une voix. Toutes les IA. Toutes les actions.</span><span>© 2026 VOXA</span></footer>
  <AnimatePresence>{demo&&<motion.div className="modal-back" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal" initial={{y:20,opacity:0}} animate={{y:0,opacity:1}}><button className="close" onClick={()=>setDemo(false)}><X/></button><div className="modal-icon"><Zap/></div><h2>VOXA est prêt à vous écouter.</h2><p>Cette version de démonstration présente l’expérience. L’application complète connectera votre voix, vos IA et les actions autorisées sur votre appareil.</p><button className="primary" onClick={()=>{setDemo(false);document.querySelector('#demo')?.scrollIntoView({behavior:'smooth'})}}>Lancer la démo <Play size={16}/></button></motion.div></motion.div>}</AnimatePresence>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
